#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if .Values.certificates.external.secret.enabled }}
{{ $caSecretName:= include "caSecret.name" . }}
{{ $caSecret:= lookup "v1" "Secret" .Release.Namespace $caSecretName }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "caSecret.name" . }}
  labels:
  {{- include "eric-esoa-so.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-so.helm-annotations" .| nindent 4 }}
type: Opaque
data:
  tls.crt: |-
{{- if $caSecret }}
    {{ index $caSecret "data" "tls.crt" |  indent 4 }}
{{ else }}

{{- end }}
{{ end }}