#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.ingress.enabled }}
{{ if .Values.ingress.iccr.enabled }}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
  {{- include "eric-esoa-so.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-so.helm-annotations" .| nindent 4 }}
    kubernetes.io/ingress.class: {{ template "eric-esoa-so.ingressClass" . }}
  name: {{ template "eric-esoa-so.name" . }}-ingress-iccr-production
spec:
  virtualhost:
    fqdn: {{ template "eric-esoa-so.fqdn" . }}
    {{- if .Values.ingress.tls.enabled }}
    tls:
      passthrough: {{ .Values.ingress.tls.passthrough }}
      secretName: {{ required "A valid .Values.ingress.tls.secretName entry required" .Values.ingress.tls.secretName }}
    {{- end }}
  includes:
    - name: eric-esoa-so-nssmf-agent-httpproxy
    - name: eric-esoa-so-dashboard-httpproxy
    - name: eric-esoa-so-catalog-manager-httpproxy
    - name: eric-esoa-so-orch-gui-httpproxy
    - name: eric-esoa-so-orchestrationcockpit-httpproxy
    - name: eric-bss-bam-authn-proxy
    - name: eric-bos-esoa-platform-onboarding-httpproxy
    - name: eric-esoa-so-key-management-agent-httpproxy
    - name: eric-esoa-so-domain-orch-adapter-httpproxy
{{- end }}
{{- end }}
