#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-esoa-so.name" . }}-sa
  labels:
    app: {{ template "eric-esoa-so.name" . }}
    chart: {{ template "eric-esoa-so.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- include "eric-esoa-so.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-esoa-so.helm-annotations" .| nindent 4 }}
automountServiceAccountToken: false
