#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#


{{- if index .Values "eric-oss-domain-orch-adapter" "enabled" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-esoa-so.name" . }}-domain-orch-adapter-rbac-configmap
  labels:
    app: {{ template "eric-esoa-so.name" . }}
  {{- include "eric-esoa-so.kubernetes-io-info" .| nindent 4 }}
    com.ericsson.bss/bam-global-rbac: {{ .Values.rbac.label }}
  annotations:
  {{- include "eric-esoa-so.helm-annotations" .| nindent 4 }}
data:
  rbac: |
    policy:
      domain-adapter-admin-1:
        PType: p
        V0: SOProviderAdmin
        V1: /v1/notifications*
        V2: get
      domain-adapter-admin-2:
        PType: p
        V0: SOProviderAdmin
        V1: /v1/notifications*
        V2: create
      domain-adapter-admin-3:
        PType: p
        V0: SOProviderAdmin
        V1: /v1/notifications*
        V2: update
      domain-adapter-admin-4:
        PType: p
        V0: SOProviderAdmin
        V1: /v1/notifications*
        V2: delete
      domain-adapter-user-1:
        PType: p
        V0: SOUser
        V1: /v1/notifications*
        V2: get
      domain-adapter-user-2:
        PType: p
        V0: SOUser
        V1: /v1/notifications*
        V2: create
      domain-adapter-user-3:
        PType: p
        V0: SOUser
        V1: /v1/notifications*
        V2: update
      domain-adapter-user-4:
        PType: p
        V0: SOUser
        V1: /v1/notifications*
        V2: delete
      domain-adapter-designer-1:
        PType: p
        V0: SODesigner
        V1: /v1/notifications*
        V2: get
      domain-adapter-designer-2:
        PType: p
        V0: SODesigner
        V1: /v1/notifications*
        V2: create
      domain-adapter-designer-3:
        PType: p
        V0: SODesigner
        V1: /v1/notifications*
        V2: update
      domain-adapter-designer-4:
        PType: p
        V0: SODesigner
        V1: /v1/notifications*
        V2: delete
      domain-adapter-readOnly-1:
        PType: p
        V0: SOReadOnly
        V1: /v1/notifications*
        V2: get


{{- end }}
