#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if index .Values "eric-eo-catalog-manager" "enabled"}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "eric-esoa-so.name" . }}-catalog-manager-rbac-configmap
  labels:
    app: {{ template "eric-esoa-so.name" . }}
  {{- include "eric-esoa-so.kubernetes-io-info" .| nindent 4 }}
    com.ericsson.bss/bam-global-rbac: {{ .Values.rbac.label }}
  annotations:
  {{- include "eric-esoa-so.helm-annotations" .| nindent 4 }}
data:
  rbac: |
    policy:
      catalog-user-1:
        PType: p
        V0: SOUser
        V1: /catalog-manager/*
        V2: get
      catalog-user-2:
        PType: p
        V0: SOUser
        V1: /catalog-manager/*
        V2: create
      catalog-user-3:
        PType: p
        V0: SOUser
        V1: /catalog-manager/*
        V2: delete
      catalog-read-only-1:
        PType: p
        V0: SOReadOnly
        V1: /catalog-manager/*
        V2: get
      catalog-admin-1:
        PType: p
        V0: SOProviderAdmin
        V1: /catalog-manager/*
        V2: get
      catalog-admin-2:
        PType: p
        V0: SOProviderAdmin
        V1: /catalog-manager/*
        V2: create
      catalog-admin-3:
        PType: p
        V0: SOProviderAdmin
        V1: /catalog-manager/*
        V2: delete
      catalog-designer-1:
        PType: p
        V0: SODesigner
        V1: /catalog-manager/*
        V2: get
      catalog-designer-2:
        PType: p
        V0: SODesigner
        V1: /catalog-manager/*
        V2: create
      catalog-designer-3:
        PType: p
        V0: SODesigner
        V1: /catalog-manager/*
        V2: delete

{{- end }}
